services:
  db:
    image: mongo
    container_name: db
    restart: always
    volumes:
      - data:/data/db
    ports:
      - 27017:27017

  api:
    build: .
    container_name: api
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command:
    - sh
    - -c
    - |
      npm run start

volumes:
  data:
